const cars = [
    {
        brand: "Tesla",
        model: "Model S",
        year: 2023,
        price: "$89,990",
        color: "Red",
        horsepower: 670,
        image: "tesla-model-s.jpg",
    },
    {
        brand: "BMW",
        model: "X5",
        year: 2022,
        price: "$61,600",
        color: "Black",
        horsepower: 335,
        image: "bmw-x5.jpg",
    },
    {
        brand: "Audi",
        model: "A6",
        year: 2023,
        price: "$56,000",
        color: "White",
        horsepower: 261,
        image: "audi-a6.jpg",
    },
    {
        brand: "Mercedes-Benz",
        model: "C-Class",
        year: 2023,
        price: "$44,850",
        color: "Blue",
        horsepower: 255,
        image: "mercedes-c-class.jpg",
    },
    {
        brand: "Ford",
        model: "Mustang",
        year: 2023,
        price: "$30,920",
        color: "Yellow",
        horsepower: 450,
        image: "ford-mustang.jpg",
    },
    {
        brand: "Toyota",
        model: "Camry",
        year: 2023,
        price: "$26,320",
        color: "Gray",
        horsepower: 203,
        image: "toyota-camry.jpg",
    },
    {
        brand: "Tesla",
        model: "Model S",
        year: 2023,
        price: "$89,990",
        color: "Red",
        horsepower: 670,
        image: "tesla-model-s.jpg",
    },
    {
        brand: "BMW",
        model: "X5",
        year: 2022,
        price: "$61,600",
        color: "Black",
        horsepower: 335,
        image: "bmw-x5.jpg",
    },
    {
        brand: "Audi",
        model: "A6",
        year: 2023,
        price: "$56,000",
        color: "White",
        horsepower: 261,
        image: "audi-a6.jpg",
    },
    {
        brand: "Mercedes-Benz",
        model: "C-Class",
        year: 2023,
        price: "$44,850",
        color: "Blue",
        horsepower: 255,
        image: "mercedes-c-class.jpg",
    },
    {
        brand: "Ford",
        model: "Mustang",
        year: 2023,
        price: "$30,920",
        color: "Yellow",
        horsepower: 450,
        image: "ford-mustang.jpg",
    },
    {
        brand: "Toyota",
        model: "Camry",
        year: 2023,
        price: "$26,320",
        color: "Gray",
        horsepower: 203,
        image: "toyota-camry.jpg",
    },
    {
        brand: "Honda",
        model: "Civic",
        year: 2023,
        price: "$24,650",
        color: "Silver",
        horsepower: 180,
        image: "honda-civic.jpg",
    },
    {
        brand: "Chevrolet",
        model: "Corvette",
        year: 2023,
        price: "$65,895",
        color: "Orange",
        horsepower: 495,
        image: "chevrolet-corvette.jpg",
    },
    {
        brand: "Porsche",
        model: "911 Carrera",
        year: 2023,
        price: "$106,100",
        color: "White",
        horsepower: 379,
        image: "porsche-911.jpg",
    },
    {
        brand: "Hyundai",
        model: "Elantra",
        year: 2023,
        price: "$20,950",
        color: "Blue",
        horsepower: 147,
        image: "hyundai-elantra.jpg",
    },
    {
        brand: "Kia",
        model: "Sorento",
        year: 2023,
        price: "$30,090",
        color: "Green",
        horsepower: 191,
        image: "kia-sorento.jpg",
    },
    {
        brand: "Mazda",
        model: "CX-5",
        year: 2023,
        price: "$27,550",
        color: "Red",
        horsepower: 187,
        image: "mazda-cx5.jpg",
    },
    {
        brand: "Volkswagen",
        model: "Passat",
        year: 2022,
        price: "$27,295",
        color: "Black",
        horsepower: 174,
        image: "volkswagen-passat.jpg",
    },
    {
        brand: "Jeep",
        model: "Wrangler",
        year: 2023,
        price: "$34,045",
        color: "Gray",
        horsepower: 285,
        image: "jeep-wrangler.jpg",
    },
    {
        brand: "Nissan",
        model: "Altima",
        year: 2023,
        price: "$25,290",
        color: "Silver",
        horsepower: 188,
        image: "nissan-altima.jpg",
    },
];

const container = document.getElementById("car-container");
let template = ``;
container.innerHTML = template;
for (const car of cars) {
    template += `
        <div class="car-card">
            <h3>${car.brand} ${car.model}</h3>
            <p>Year: ${car.year}</p>
            <p>Price: ${car.price}</p>
            <p>Color: ${car.color}</p>
            <p>Horsepower: ${car.horsepower} HP</p>
        </div>
    `;
}
container.innerHTML = template;
